# Generated by Django 3.0.6 on 2020-07-10 13:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('mob', models.CharField(max_length=50)),
                ('textarea', models.TextField(default='', max_length=10000)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('title_desc', models.CharField(max_length=400)),
                ('Type', models.CharField(choices=[('Breaking', 'BREAKING'), ('Latest', 'LATEST'), ('Top', 'TOP')], max_length=30)),
                ('category', models.CharField(choices=[('India', 'INDIA'), ('World', 'WORLD'), ('Election', 'ELECTION'), ('Business', 'BUSINESS'), ('Tech', 'TECH'), ('Science', 'SCIENCE'), ('Health', 'HEALTH'), ('Entertainment & Arts', 'ENTERTAINMENT & ARTS')], max_length=30)),
                ('image', models.ImageField(upload_to='news_app/images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('datetime', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sports_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_desc', models.CharField(max_length=300)),
                ('Type', models.CharField(choices=[('Breaking', 'BREAKING'), ('Latest', 'LATEST'), ('Top', 'TOP')], max_length=30)),
                ('category', models.CharField(choices=[('Cricket', 'CRICKET'), ('Football', 'FOOTBALL'), ('Hockey', 'HOCKEY'), ('Kabaddi', 'KABADDI'), ('Basketball', 'BASKETBALL'), ('Others', 'OTHERS')], max_length=30)),
                ('image', models.ImageField(upload_to='news_app/images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('datetime', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('Tv_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_embed', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'TV',
                'verbose_name_plural': 'TV',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=300)),
                ('video', models.FileField(upload_to='news_app/videos')),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='news_app/images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weather',
            },
        ),
    ]
