name: Webapp CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: webapp
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::484478223226:role/github-actions

      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${GITHUB_SHA::7} .

      - name: Push Docker image
        run: |
          docker tag $IMAGE_NAME:${GITHUB_SHA::7} $DOCKER_USERNAME/$IMAGE_NAME:${GITHUB_SHA::7}
          docker push $DOCKER_USERNAME/$IMAGE_NAME:${GITHUB_SHA::7}
      
      - name: Modify Image Tag Inside Helm
        run: |
          TAG_VALUE=${GITHUB_SHA::7}
          sed -i "s/tag: .*/tag: $TAG_VALUE/" ./helm/values.yaml

      - name: Install Helm Chart
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.4
        with:
          aws-region: eu-west-2
          cluster-name: assesment-eks-cluster
          config-files: ./helm/values.yaml
          chart-path: ./helm/
          name: assesment
